apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.muge.net
spec:
  scope: Namespaced
  group: muge.net
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Database
    plural: databases
    singular: database
    shortNames:
      - db
      - dbs
  additionalPrinterColumns:
    - name: Type
      type: string
      priority: 0
      JSONPath: .spec.type
      description: The type of the database that should be created
    - name: Tag
      type: string
      priority: 0
      JSONPath: .spec.tag
      description: Image tag
