apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: default
  labels:
    app: operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: kopf-operator
      containers:
      - image: "gcr.io/$PROJECT_ID/operator:latest"
        name: operator
